
name: cine1895_camera
description: A VFX overlay camera for on-set use.

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0+4
  video_player: ^2.4.5
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  wakelock: ^0.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/
