
name: cine1895_camera
description: On-set VFX overlay camera (Android first).

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  video_player: ^2.8.6
  file_picker: ^8.0.3
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  gallery_saver: ^2.3.2
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
